spring.thymeleaf.cache: false

spring:
  datasource:
    url: jdbc:mysql://mysql.stud.iie.ntnu.no:3306/g_scrum05
    username: g_scrum05
    password: ${scrum5_dbpw}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties.hibernate.current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext


